name: "Test"
on:
  workflow_dispatch:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#image --extra-experimental-features nix-command --extra-experimental-features flakes
    - run: nix-shell -p skopeo --command "echo ${{ secrets.GITHUB_TOKEN }} | skopeo login -u ${{ github.actor }} --password-stdin codeberg.org && skopeo --insecure-policy copy docker-archive:./result docker://ghcr.io/saturn745/divine-intellect-telegram:latest"
